### ISSUE TITLE
User replies to annotations are duplicated 

### ISSUE THREAD

**Issue by nrussell96** [ycp-cjkn/ToBeRenamed#83]
Issue occurs in GetSignedInMemberHandler
This occured after 20a2b590ff5355ba9ecb562283125800514feb6d where we attempted to fix the bug of not being able to have multiple libraries (I didn't end up pushing that commit to master)

**Comment by kjones7** [comment]
Fixed bug here: a35ec00ce70395ae6e795b59a7ed73db5be07351
